# --------------------------------------- 
# Module: ee11-quickstart
# Enables the Jetty Quickstart module for rapid deployment of preconfigured web applications.
# --------------------------------------- 
--modules=ee11-quickstart


# Modes are AUTO, GENERATE, QUICKSTART
# jetty.quickstart.mode=AUTO
# jetty.quickstart.origin=origin
# jetty.quickstart.xml=

