#!/bin/bash
#
#  SPDX-FileCopyrightText: 2023 Bill Ross <phobrain@sonic.net>
#
#  SPDX-License-Identifier: CC-BY-SA-4.0
#

set -e

time java -Xmx64g -jar build/libs/histogram-all-1.0.jar $*

echo ran
